### ISSUE TITLE
I am absolutely in love with this

### ISSUE THREAD

**Issue by GabrielFoxDev** [x653/xv6-riscv-fpga#1]
I could've just sent an e-mail thanking you for all the effort put into piecing everything together, but I feel like such an undertaking deserves public acknowledgement and praise.

So thanks! Thank you so very much!
This is awesome, it's amazing, fantastic, marvelous, surreal.

: )

**Comment by x653** [comment]
Hi there,
Thanks for your nice words.
Best
Micha

Am 29. September 2023 17:10:33 MESZ schrieb "GabrielFox.Dev" ***@***.***>:
>I could've just sent an e-mail thanking you for all the effort put into piecing everything together, but I feel like such an undertaking deserves public acknowledgement and praise.
>
>So thanks! Thank you so very much!
>This is awesome, it's amazing, fantastic, marvelous, surreal.
>
>: )
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/x653/xv6-riscv-fpga/issues/1
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Michael Schröder
